const constants = {
  USER_JOINED : "USER_JOINED",
  USER_LEFT : "USER_LEFT",
  SEND_MESSAGE : "SEND_MESSAGE",
  REMOVE_MESSAGE : "REMOVE_MESSAGE",
  RECEIVE_MESSAGE : "RECEIVE_MESSAGE",
  REPLY_MESSAGE : "REPLY_MESSAGE",
  FETCH_MESSAGES : "FETCH_MESSAGES",
  CANCEL_FETCHING : "CANCEL_FETCHING",
  INPUT_SUBMITTED: "INPUT_SUBMITTED",
  INPUT_CHANGED: "INPUT_CHANGED",
  SHOW_EMOTICONS: "SHOW_EMOTICONS",
  HIDE_EMOTICONS: "HIDE_EMOTICONS",
  BUDDY_JOINED : "BUDDY_JOINED",
  BUDDY_LEFT : "BUDDY_LEFT",
  ADD_ERROR : "ADD_ERROR",
  CLEAR_ERROR : "CLEAR_ERROR",
  OPEN_INFO : "OPEN_INFO",
  CLOSE_INFO : "CLOSE_INFO"
}

export default constants
