const constants = {
  USER_JOINED : "USER_JOINED",
  USER_LEFT : "USER_LEFT",
  SEND_MESSAGE : "SEND_MESSAGE",
  REMOVE_MESSAGE : "REMOVE_MESSAGE",
  RECEIVE_MESSAGE : "RECEIVE_MESSAGE",
  FETCH_MESSAGES : "FETCH_MESSAGES",
  CANCEL_FETCHING : "CANCEL_FETCHING",
  BUDDY_JOINED : "BUDDY_JOINED",
  BUDDY_LEFT : "BUDDY_LEFT",
  ADD_ERROR : "ADD_ERROR",
  CLEAR_ERROR : "CLEAR_ERROR"
}

export default constants
